# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L93ZS2jlC3tlVw7DT2iQSuDXXTF10bpE
"""

#1 Find Sum of First 10 Natural Numbers
sum = 0

for i in range(1, 11):
    sum = sum + i

print("Sum of first 10 natural numbers =", sum)

#2 Find Factorial of a Number
num = int(input("Enter a number: "))

fact = 1

for i in range(1, num + 1):
    fact = fact * i

print("Factorial =", fact)

#3 Print Fibonacci Series
n = int(input("Enter number of terms: "))

a = 0
b = 1

print("Fibonacci Series:")

for i in range(n):
    print(a, end=" ")
    c = a + b
    a = b
    b = c

#4 Find Largest Among 3 Numbers
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))

if a >= b and a >= c:
    largest = a
elif b >= a and b >= c:
    largest = b
else:
    largest = c

print("Largest number =", largest)

#5 Student Result System
# Student Result System

name = input("Enter Student Name: ")
roll_no = input("Enter Roll Number: ")

total = 0

# Input marks of 5 subjects
for i in range(1, 6):
    marks = float(input("Enter marks of Subject " + str(i) + ": "))
    total = total + marks

# Calculate percentage
percentage = total / 5

# Calculate grade
if percentage >= 90:
    grade = "A+"
elif percentage >= 80:
    grade = "A"
elif percentage >= 70:
    grade = "B"
elif percentage >= 60:
    grade = "C"
elif percentage >= 50:
    grade = "D"
else:
    grade = "F"

# Display Result
print("\n----- STUDENT RESULT -----")
print("Name:", name)
print("Roll No:", roll_no)
print("Total Marks:", total)
print("Percentage:", percentage, "%")
print("Grade:", grade)