# -*- coding: utf-8 -*-
"""Assignment 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fajlzqGroX3tfXCDmZo4qRNTR_iLec48
"""

#Load the dataset and display the first five records.

import pandas as pd

# Load the dataset
df = pd.read_csv('Dataset 2.csv')

# Display the first 5 records
df.head()

#Determine the number of rows and columns in the dataset.

print("Dataset shape:", df.shape)

#Display all column names.

print("Columns in dataset:", df.columns.tolist())

#Identify numerical and categorical features.

df.info()

#Identify numerical and categorical features.

df.isnull().sum()

#Calculate the average age of users.
avg_age = df['Age'].mean()
print(f"Average Age: {avg_age:}")

#Determine the average watch hours per week.
avg_watch_hours = df['WatchHoursPerWeek'].mean()
print(f"Average Watch Hours/Week: {avg_watch_hours:}")

#Find the average monthly spending of users.
avg_monthly_spend = df['MonthlySpend'].mean()
print(f"Average Monthly Spend: {avg_monthly_spend:}")

#Count the number of users in each subscription category.
df['SubscriptionType'].value_counts()

#Determine the percentage of users who renewed their subscriptions.
renewal_pct = df['SubscriptionRenewed'].value_counts(normalize=True) * 100
print(renewal_pct)

#Convert categorical features into numerical form.
from sklearn.preprocessing import LabelEncoder
df_encoded = df.copy()

# Initialize LabelEncoder
le = LabelEncoder()

# List of categorical columns to convert
categorical_cols = ['Gender', 'SubscriptionType', 'FavoriteGenre', 'SubscriptionRenewed']

for col in categorical_cols:
    df_encoded[col] = le.fit_transform(df_encoded[col])

# Viewing the converted data
df_encoded.head()

#Define the feature set (X) and target variable (y) for subscription renewal prediction.
y = df_encoded['SubscriptionRenewed']

# Features (X) are all other relevant columns
X = df_encoded.drop(columns=['UserID', 'SubscriptionRenewed'])

#Split the dataset into training and testing sets.
from sklearn.model_selection import train_test_split

#Spliting 80% for training and 20% for testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training set size: {X_train.shape[0]} rows")
print(f"Testing set size: {X_test.shape[0]} rows")

#Train a Decision Tree model to predict whether a user will renew their subscription.
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Initialize the model
dt_model = DecisionTreeClassifier(random_state=42)

# Train the model
dt_model.fit(X_train, y_train)

#Evaluate the model using accuracy.
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Initialize the model
dt_model = DecisionTreeClassifier(random_state=42)

# Train the model
dt_model.fit(X_train, y_train)

# Predict on the test set
dt_preds = dt_model.predict(X_test)

# Evaluate accuracy
dt_acc = accuracy_score(y_test, dt_preds)
print(f"Decision Tree Accuracy: {dt_acc * 100:}%")

#Generate and interpret the confusion matrix.
from sklearn.metrics import confusion_matrix, classification_report

cm = confusion_matrix(y_test, dt_preds)
print("Confusion Matrix:")
print(cm)
print("\nClassification Report:")
print(classification_report(y_test, dt_preds))

#Train a KNN classifier with K = 5.
#Compare the accuracy of KNN with the Decision Tree model.
from sklearn.neighbors import KNeighborsClassifier

# Initialize and train KNN
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)

# Predict and evaluate
knn_preds = knn_model.predict(X_test)
knn_acc = accuracy_score(y_test, knn_preds)

print(f"KNN Accuracy: {knn_acc * 100:.2f}%")
print(f"Decision Tree Accuracy: {dt_acc * 100:.2f}%")

#Train a Linear Regression model to predict monthly spending.
from sklearn.linear_model import LinearRegression

X_reg = df_encoded.drop(columns=['UserID', 'MonthlySpend'])
y_reg = df_encoded['MonthlySpend']

X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(X_reg, y_reg, test_size=0.2, random_state=42)

reg_model = LinearRegression()
reg_model.fit(X_train_r, y_train_r)
print("Linear Regression model successfully trained!")

#Predict the monthly spending for a new user and interpret the result.

#Creating a hypothetical user based on the features in X_reg
import numpy as np

# Creating fake data matching our columns length
sample_user = np.array([[30, 0, 1, 15, 3, 2, 12, 0]])

predicted_spend = reg_model.predict(sample_user)
print(f"Predicted Monthly Spending for the user: {predicted_spend[0]:.2f}")

"""Business Reflection Questions  
1. Which factors appear to influence subscription renewal the most?  
2. Why is subscription renewal a classification problem?  
3. Why is monthly spending a regression problem?  
4. Which algorithm performed better for renewal prediction?  
5. How could the platform use these predictions to improve customer retention?

Ans 1:
-Watch Hours Per Week: Users who actively watch
content (high watch hours) consistently renew their subscriptions. If they aren't using the platform, they cancel.  
-Subscription Type: Users on Premium and VIP tiers tend to have higher renewal rates compared to Basic plan users, likely because they are more invested in the platform.  
-Ad Clicks: Interestingly, high ad-click counts Often correlate with lower renewal rates, as too many interruptions can ruin the user experience.  

Ans 2:
Subscription renewal is a classification problem because the outcome we are trying to predict is a category, not a number. The user either renews or they don’t—it is a strict Yes or No (binary) choice. Machine learning classification models are specifically designed to sort data points into these kinds of distinct buckets.  

Ans 3: Monthly spending is a regression problem because the value we want to predict is a continuous numeric value. A user's spend isn't a simple label; it can be any amount on a continuous scale. Regression algorithms are used whenever you need to predict a precise numerical quantity rather than a group or category.  

Ans 4: Based on testing this specific type of structured user data, the Decision Tree Classifier generally outperforms the K-Nearest Neighbors (KNN) model for this task.Decision Trees are excellent at handling a mix of text and numbers (like Gender, Subscription Type, and Watch Hours) and creating clear "if-then" rules.  KNN can struggle here because the data features have very different scales (e.g., Age ranges from 18–65, while Devices Used only ranges from 1–5), which throws off its distance-based calculations.  

Ans 5: -Early Warning System: If the model flags a user as "Likely to Churn" (No Renewal), the platform can automatically trigger a targeted email with a special discount or a preview of upcoming seasons of their favorite genre.  
-Boost Low Engagement: For users whose watch When hours drop below a certain threshold, the system can send personalised push notifications recommending trending shows to get them watching again.  
-Plan Upgrades: Since Premium/VIP users stick around longer, the marketing team can offer tailored, low-cost trials to Basic users to upgrade their tiers.
"""