# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tejC08qk1s2h3Fk1MGPfL-iBtvImY9vh

Find area of rectangle.
"""

length=int(input("Enter the lenght:"))
breadth=int(input("Enter the breadth:"))
area=length*breadth
print("The area of the rectangle is ",area)

"""Find simple interest."""

P=int(input("Enter the principle:"))
R=int(input("Enter the interest rate:"))
T=int(input("Enter the time in years:"))
s=(P*R*T)/100
print("Simple interest is ",s)

celsius = float(input("Enter temperature in Celsius: "))

fahrenheit = (celsius * 9/5) + 32
print(f"{celsius}°C is equal to {fahrenheit}°F")

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
num3 = float(input("Enter third number: "))

average = (num1 + num2 + num3) / 3
print(f"The average is: {average}")

num = float(input("Enter a number: "))

square = num ** 2
cube = num ** 3

print(f"Square: {square}")
print(f"Cube: {cube}")

a = float(input("Enter first number (a): "))
b = float(input("Enter second number (b): "))

# Pythonic tuple assignment swapping
a, b = b, a

print(f"After swapping: a = {a}, b = {b}")

# Take student details
name = input("Enter student name: ")
roll_number = input("Enter roll number: ")

# Store marks in variables
maths = float(input("Enter Maths marks: "))
science = float(input("Enter Science marks: "))
english = float(input("Enter English marks: "))

# Calculate total and percentage
total_marks = maths + science + english
percentage = (total_marks / 300) * 100

# Display report card
print("\n--- Student Report Card ---")
print(f"Name: {name}")
print(f"Roll Number: {roll_number}")
print(f"Total Marks Obtained: {total_marks} / 300")
print(f"Percentage: {percentage:.2f}%")